# Sign Up Page for New Company
REG_LINK = 'id:login-register-new-company'
REG_PAGE = 'id:register-wrapper'
REG_COMPANY_NAME = 'id:reg-company-name'
REG_NAME = 'id:reg-name'
REG_EMAIL = 'id:reg-email'
REG_PASSWORD = 'id:reg-password'
REG_PRIVACY_POLICY = 'id:reg-privacy-policy'
REG_CREATE_ACCOUNT = 'id:reg-create-account'
REG_VIEW_PASSWORD = 'id:reg-view-password'
REG_INV_PASS_AT_LEAST_8_CHAR = 'id:reg-password-must-be-8-characters'
REG_INV_EMAIL = 'id:reg-must-be-a-valid-email'
REG_INV_FORMAT = 'id:reg-password-must-be-valid-format'
REG_PASS_MAX_LIMIT = 'id:reg-password-must-be-not-more-than-50-characters'
REG_COMPANY_NAME_MAX_LIMIT = 'id:reg-company-name-must-be-not-more-than-100-characters'
REG_NAME_MAX_LIMIT = 'id:reg-name-must-be-not-more-than-100-characters'
REG_EMAIL_MAX_LIMIT = 'id:reg-email-must-be-not-more-than-100-characters'
REG_PASSWORD_MAX_LIMIT = 'id:reg-password-must-be-not-more-than-50-characters'

REG_REQUIRED_FIELD_COMPANY_NAME = 'id:reg-company-name-field-is-required'
REG_REQUIRED_FIELD_NAME = 'id:reg-name-field-is-required'
REG_REQUIRED_FIELD_EMAIL = 'id:reg-email-field-is-required'
REG_REQUIRED_FIELD_PASSWORD = 'id:reg-password-field-is-required'
REG_REGISTER_HERE = 'id:register-new-candidate'
REG_APPLICANT_PAGE = 'id:register-wrapper'

